### ISSUE TITLE
Ledger wallet, not able to withdraw

### ISSUE THREAD

**Issue by ulwima** [ArdentHQ/arkvault#276]
### Describe the Bug

Not able to withdraw from a ledger wallet. I can load the wallet from the ledger, but when I try to withdraw nothing happens. Just the cursor spinning. This is on Mint/Linux, and I tried Brave, Chromium and Vivaldi. Same behavior, the app first connect to the ledger, so I can see the balance, but I am not able to withdraw.
I tried to change my delegate-vote, and that worked.
Last time I was able to withdraw was 10. December.

I also tried on Windows, Firefox and Edge browser. There I get an error-message: 'e.openConnected is not a function'.

I have used two ledger devices, first a Ledger Nano S, and than a Ledger Nano X. Same behavior, both on Linux and Windows.

Update:
I am still not able to withdraw from the Ledger-wallet to any 'outside' wallet. However I created a new wallet in the vault-app, using the code-words from Ledger. and I was able to transfer from the Ledger-wallet to the new wallet, and from that wallet and out to an external wallet, using the mnemonic words.

### Expected Behavior

Expect to be able to withdraw funds.

### To Reproduce

Go to 'Send Ark'-page.
Enter sender and recipient addresses. Enter amount. 
No Memo. Average  Average transaction fee.
Click Continue.
Sent to 'Transaction review' page.
Click Continue.
Sent to the 'Ledger Wallet' page.
Sees a spinning circle, and the message 'Open the ARK app on your device.
But it never connects.

### What operating system are you using?

Linux

### What browser are you using?

Brave, Chromium, and Vivaldi

### What version of Node.js are you using?

Using the web-version.

**Comment by ulwima** [comment]
Ledger Firmware is 2.0.2, and Ark app version on the ledger is 2.3.0.
I made another attempt, and I was still not able to transfer from the ledger account to an exchange, which I have transferred to before.
I was however able to transfer from the ledger account to an account made in the ArkVault, from the same code words that are used on the Ledger.

**Comment by samharperpittam** [comment]
Thanks for the response @ulwima ,

When attempting to send a transaction using your Ledger device, do you have any other applications open that may also be connected to your Ledger such as Ledger Live?

If so, could you please try closing all other applications and attempt a transaction again. 

Thanks

**Comment by ulwima** [comment]
I tried to withdraw again to an external wallet again today, and now it worked. So this is solved for me.
If nobody else has had any problem, I see no reason to not close the issue.
I have tried with an other ledger, and that worked without any problem.
