### ISSUE TITLE
[Profile Export] Color Accent not respected

### ISSUE THREAD

**Issue by samharperpittam** [ArdentHQ/arkvault#53]
### Describe the Bug

When importing a profile that uses the Green accent color, the color defaults back to blue. It appears the setting is not respected during export. 

### Expected Behavior

Respect the accent color

### To Reproduce

- Create profile
- Change color to green
- Export profile
- Import profile

### What operating system are you using?

macOS

### What browser are you using?

Chrome

**Comment by dated** [comment]
Interestingly enough this appears to happen only when accessing the profile for the first time. After logging out and accessing the profile again it appears as expected. The accent color is restored and imported correctly, it just isn't applied right away.
